#Docker file based on latest CentOS 7 image
FROM centos:latest
MAINTAINER Mark.Fieldhouse@mafitconsulting.co.uk

RUN useradd -ms /bin/bash user

ENTRYPOINT echo "This command will display this message on EVERY container"

USER user

