#Docker file based on latest CentOS 7 image
FROM centos:latest
MAINTAINER Mark.Fieldhouse@mafitconsulting.co.uk

RUN useradd -ms /bin/bash user

CMD "echo" "This is a custom container message"

USER user

